### ISSUE TITLE
replace jquery with a lighter library

### ISSUE THREAD

**Issue by mgeraci** [mgeraci/hangboard-timer#2]
I'm only using the most basic of jquery functions here, so a sizzle should work fine and save some page weight.

**Comment by hachibu** [comment]
:+1:

**Comment by mgeraci** [comment]
Hmm, this might be a `wontfix` for now; sizzle is just the selector engine, and I'm also using event binding from jQuery (`$("body").on("click", ".foo", function() { ... }`)

**Comment by hachibu** [comment]
@mgeraci consider using https://github.com/madrobby/zepto

**Comment by mgeraci** [comment]
Wow, zepto turned out to be a literal drop-in replacement. Thanks @hachibu!

**Comment by mgeraci** [comment]
fixed in 656add55a821fec5609e9da922dd94fa4268964d

**Comment by hachibu** [comment]
awesome
