### ISSUE TITLE
Recovery display is funky

### ISSUE THREAD

**Issue by hachibu** [mgeraci/hangboard-timer#8]
![screen shot 2016-12-19 at 2 14 53 pm](https://cloud.githubusercontent.com/assets/10385848/21331083/94917048-c5f5-11e6-9eaf-4fff9c7cbe19.png)

**Comment by mgeraci** [comment]
yeah, fixing the default now...

**Comment by mgeraci** [comment]
Fixed in fe5b5e6fc4ff146504dfe4eed03bfce448a87d0a, though your weird value will be in localstorage. You can remove it by pasting `localStorage.removeItem("formValues")` into your js console.

**Comment by hachibu** [comment]
@mgeraci awesome, fixed!
